# Generated by Django 3.2.10 on 2021-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_alter_articleinfo_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInf',
            fields=[
                ('articleid', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleInfo',
        ),
    ]
